# Generated by Django 5.1.4 on 2025-01-23 21:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('fecha_generacion', models.DateField()),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HorarioLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(max_length=255)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('sin_supervision', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('laboratorio', 'fecha_reserva', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad Disponible')),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.CharField(blank=True, max_length=36, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cambiada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cambio', models.DateField()),
                ('tipo_cambio', models.CharField(max_length=50)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('laboratorio', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=50)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.subcategoria'),
        ),
        migrations.CreateModel(
            name='DetalleTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_caracteristica', models.TextField(blank=True, null=True)),
                ('num_cat', models.TextField(blank=True, null=True)),
                ('num_serie', models.TextField(blank=True, null=True)),
                ('modelo', models.TextField(blank=True, null=True)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('articulo', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.categoria')),
                ('inventario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_tecnico', to='appGestionInventario.inventario')),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='DatosComplementarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.TextField(blank=True, null=True)),
                ('accesorios', models.TextField(blank=True, null=True)),
                ('medidas', models.TextField(blank=True, null=True)),
                ('colores', models.TextField(blank=True, null=True)),
                ('capacidad', models.TextField(blank=True, null=True)),
                ('informacionAdicional', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.categoria')),
                ('inventario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos_complementarios', to='appGestionInventario.inventario')),
                ('subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='UsoItemLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_uso', models.DateField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.inventario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.solicitudlaboratorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='solicitudlaboratorio',
            index=models.Index(fields=['laboratorio'], name='idx_laboratorio_solicitudes'),
        ),
        migrations.AddIndex(
            model_name='usoitemlaboratorio',
            index=models.Index(fields=['fecha_uso'], name='idx_fecha_uso'),
        ),
    ]
