# Generated by Django 5.1.2 on 2024-11-12 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_caracteristica', models.TextField(blank=True)),
                ('num_cat', models.CharField(blank=True, max_length=50)),
                ('num_serie', models.CharField(blank=True, max_length=25)),
                ('modelo', models.CharField(blank=True, max_length=25)),
                ('accesorios', models.TextField(blank=True)),
                ('medidas', models.CharField(blank=True, max_length=50)),
                ('colores', models.CharField(blank=True, max_length=50)),
                ('capacidad', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reporte', models.CharField(max_length=50)),
                ('fecha_generacion', models.DateField()),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo', models.CharField(blank=True, max_length=50, unique=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appGestionInventario.categoria')),
                ('detalle_tecnico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appGestionInventario.detalletecnico')),
            ],
        ),
        migrations.CreateModel(
            name='InformacionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.TextField(blank=True)),
                ('presentacion', models.TextField(blank=True)),
                ('articulo', models.CharField(blank=True, max_length=50)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cambiada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cambio', models.DateField()),
                ('tipo_cambio', models.CharField(max_length=50)),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=36)),
                ('vencimiento', models.DateField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.inventario')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('laboratorio', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=50)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id_subcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='subcategoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appGestionInventario.subcategoria'),
        ),
        migrations.CreateModel(
            name='UsoItemLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_uso', models.DateField()),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.inventario')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.solicitudlaboratorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='solicitudlaboratorio',
            index=models.Index(fields=['laboratorio'], name='idx_laboratorio_solicitudes'),
        ),
        migrations.AddIndex(
            model_name='usoitemlaboratorio',
            index=models.Index(fields=['fecha_uso'], name='idx_fecha_uso'),
        ),
    ]
