# Generated by Django 5.1.2 on 2025-01-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(max_length=255)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'unique_together': {('laboratorio', 'fecha_reserva', 'hora_inicio', 'hora_fin')},
            },
        ),
    ]
