# Generated by Django 5.1.2 on 2025-01-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usoitemlaboratorio',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
