# Generated by Django 5.1.2 on 2024-10-17 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Categorias',
        ),
    ]
