# Generated by Django 5.1.2 on 2025-04-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefoto',
            name='imagen',
            field=models.ImageField(upload_to='reportes_fotos/'),
        ),
    ]
