# Generated by Django 5.1.2 on 2025-01-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0002_usoitemlaboratorio_unidad_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialinventario',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
