# Generated by Django 5.1.2 on 2024-10-23 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0002_rename_categoria_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('Categorias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionInventario.categorias')),
            ],
            options={
                'indexes': [models.Index(fields=['nombre'], name='idx_nombre_inventario')],
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad_disponible__gte', 0)), name='cantidad_disponible_gte_0')],
            },
        ),
    ]
