# Generated by Django 5.1.2 on 2025-01-22 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0002_horariolaboratorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariolaboratorio',
            name='sin_supervision',
            field=models.BooleanField(default=False),
        ),
    ]
