# Generated by Django 5.1.2 on 2025-04-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0002_alter_reportefoto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportefoto',
            name='imagen',
            field=models.ImageField(max_length=255, upload_to='reportes_fotos/'),
        ),
    ]
