# Generated by Django 5.1.2 on 2025-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0003_historialinventario_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
