# Generated by Django 5.1.2 on 2024-11-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0003_alter_categoria_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='id_subcategoria',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
