# Generated by Django 5.1.2 on 2025-01-28 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0004_alter_inventario_cantidad_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='cantidad_disponible',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Cantidad Disponible'),
        ),
    ]
