# Generated by Django 5.1.2 on 2025-01-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0005_alter_inventario_cantidad_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialinventario',
            name='cantidad_anterior',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
