# Generated by Django 5.1.2 on 2025-01-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionInventario', '0007_historialinventario_modificado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialinventario',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
