# Generated by Django 5.1.4 on 2025-05-13 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario_nuevo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_cambiada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cambio', models.DateField()),
                ('tipo_cambio', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_nuevo.producto')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laboratorio', models.CharField(max_length=255)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('sin_supervision', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('laboratorio', 'fecha_reserva', 'hora_inicio', 'hora_fin')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('laboratorio', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=50)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('tiene_recursos', models.BooleanField(default=False, verbose_name='¿Tiene recursos asignados?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudProductosInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_uso', models.DateField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('cantidad_disponible_momento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_medida_momento', models.CharField(blank=True, max_length=50, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_nuevo.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsoItemLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_utilizada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_uso', models.DateField()),
                ('cantidad_disponible_momento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unidad_medida_momento', models.CharField(blank=True, max_length=50, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_nuevo.producto')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appGestionLaboratorios.solicitudlaboratorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='solicitudlaboratorio',
            index=models.Index(fields=['laboratorio'], name='idx_laboratorio_solicitudes'),
        ),
        migrations.AddIndex(
            model_name='solicitudproductosinventario',
            index=models.Index(fields=['fecha_uso'], name='idx_fecha_solicitud_general'),
        ),
        migrations.AddIndex(
            model_name='usoitemlaboratorio',
            index=models.Index(fields=['fecha_uso'], name='idx_fecha_uso'),
        ),
    ]
