# Generated by Django 5.2.1 on 2025-05-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionLaboratorios', '0002_solicitudlaboratorio_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudlaboratorio',
            name='asignatura',
            field=models.CharField(max_length=100, verbose_name='Asignatura'),
        ),
        migrations.AlterField(
            model_name='solicitudlaboratorio',
            name='clase',
            field=models.CharField(max_length=100, verbose_name='Clase/Grado'),
        ),
    ]
