# Generated by Django 5.2.1 on 2025-05-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionLaboratorios', '0003_alter_solicitudlaboratorio_asignatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudlaboratorio',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('finalizar_uso', 'finalizar_uso')], default='pendiente', max_length=50),
        ),
    ]
