# Generated by Django 5.2.1 on 2025-05-24 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appGestionLaboratorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteUsoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_estudiantes', models.PositiveIntegerField(verbose_name='Número de Estudiantes')),
                ('estudiantes_masculinos', models.PositiveIntegerField(default=0, verbose_name='Estudiantes Masculinos')),
                ('estudiantes_femeninos', models.PositiveIntegerField(default=0, verbose_name='Estudiantes Femeninos')),
                ('horario_salida_real', models.TimeField(verbose_name='Horario Real de Salida')),
                ('fecha_generacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appGestionLaboratorios.solicitudlaboratorio', verbose_name='Solicitud Asociada')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(max_length=255, upload_to='reportes_fotos/')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='appReportes.reporteusolaboratorio')),
            ],
        ),
    ]
