# Generated by Django 5.2.1 on 2025-05-19 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appReportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteusolaboratorio',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='reporteusolaboratorio',
            name='clase',
        ),
    ]
