# Generated by Django 5.1.4 on 2025-05-25 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_nuevo', '0002_transferenciaproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariofisicodetalle',
            name='motivo_modificacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
